routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
// Settings
//Route::resource('/{type?}', 'SettingsController');
Route::group(['prefix' => 'settings', 'as' => 'settings.', 'middleware' => ['can:setting_access']], function () {
    Route::delete('destroy', 'SettingsController@massDestroy')->name('massDestroy');
    Route::prefix('{setting}/{group?}')->group(function () {
        Route::get('edit', 'SettingsController@edit')->name('edit');
        Route::get('show', 'SettingsController@show')->name('show');
        Route::match(['put', 'patch'], 'update', 'SettingsController@update')->name('update');
        Route::delete('delete', 'SettingsController@destroy')->name('destroy');
    });
    Route::prefix('{group?}')->group(function () {
        Route::get('/', 'SettingsController@index')->name('index');
        Route::get('create', 'SettingsController@create')->name('create');
        Route::post('store', 'SettingsController@store')->name('store');
    });
    Route::get('{condition?}/clear-cache', 'SettingsController@clearCache')->name('clear-cache');
    Route::post('{condition?}/save-settings', 'SettingsController@saveConditionSettings')->name('save-settings');
});

// Agent
Route::group(['prefix' => 'agents/{type}', 'as' => 'agents.'], function () {
    Route::get('/', 'AgentsController@index')->name('index');
    Route::get('create', 'AgentsController@create')->name('create');
    Route::post('store', 'AgentsController@store')->name('store');
    /* Route::prefix('{user}')->group(function () {
        Route::get('edit', 'AgentsController@edit')->name('edit');
        Route::match(['put', 'patch'], 'update', 'AgentsController@update')->name('update');
    }); */
});
Route::group(['prefix' => 'agents/{user}', 'as' => 'agents.'], function () {
    Route::prefix('{type?}')->group(function () {
        Route::get('edit', 'AgentsController@edit')->name('edit');
        Route::match(['put', 'patch'], 'update', 'AgentsController@update')->name('update');
    });
});
// Commission
Route::group(['prefix' => 'commissions', 'as' => 'commissions.', 'middleware' => ['can:commission_access']], function () {
    Route::delete('destroy', 'CommissionController@massDestroy')->name('massDestroy');
    Route::post('parse-csv-import', 'CommissionController@parseCsvImport')->name('parseCsvImport');
    Route::post('process-csv-import', 'CommissionController@processCsvImport')->name('processCsvImport');
    Route::post('getCommissionFields', 'CommissionController@returnCommissionFields')->name('returnCommissionFields');
    Route::prefix('{commission}/{type?}')->group(function () {
        Route::get('edit', 'CommissionController@edit')->name('edit');
        Route::get('show', 'CommissionController@show')->name('show');
        Route::match(['put', 'patch'], 'update', 'CommissionController@update')->name('update');
        Route::delete('delete', 'CommissionController@destroy')->name('destroy');
    });
    Route::prefix('{type?}')->group(function () {
        Route::get('/', 'CommissionController@index')->name('index');
        Route::get('create', 'CommissionController@create')->name('create');
        Route::post('store', 'CommissionController@store')->name('store');
    });
}); //Route::resource('commissions/{type?}', 'CommissionController');

// Commission Statement
Route::group(['prefix' => 'commission-statements/{type}', 'as' => 'commission-statements.'], function () {
    Route::get('/', 'CommissionStatementController@index')->name('index');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }
    return redirect()->route('admin.home');
});

Route::group(['namespace' => 'Franchiser'], function () {
    // agent email varification
    Route::get('franchiser-agent/verify/{dataSource}', 'FranchiserAgentController@verify')->name('franchiser-agent.verify');
})
;
//Color Scheme
Route::get('color-scheme-switcher/{color_scheme}','ColorSchemeController@switch')->name('color-scheme-switcher');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', '2fa']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Students
    Route::delete('students/destroy', 'StudentsController@massDestroy')->name('students.massDestroy');
    Route::resource('students', 'StudentsController');

    // Mlm Level
    Route::post('mlm-levels/parse-csv-import', 'MlmLevelController@parseCsvImport')->name('mlm-levels.parseCsvImport');
    Route::post('mlm-levels/process-csv-import', 'MlmLevelController@processCsvImport')->name('mlm-levels.processCsvImport');
    Route::resource('mlm-levels', 'MlmLevelController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Dealer
    Route::get('dealers/{user}/edit', 'DealerController@edit')->name('dealers.edit');
    Route::put('dealers/{user}/update', 'DealerController@update')->name('dealers.update');
    Route::resource('dealers', 'DealerController', ['except' => ['edit', 'update', 'show', 'destroy']]);

    // Agent Plan
    Route::delete('agent-plans/destroy', 'AgentPlanController@massDestroy')->name('agent-plans.massDestroy');
    Route::post('agent-plans/media', 'AgentPlanController@storeMedia')->name('agent-plans.storeMedia');
    Route::post('agent-plans/ckmedia', 'AgentPlanController@storeCKEditorImages')->name('agent-plans.storeCKEditorImages');
    Route::post('agent-plans/parse-csv-import', 'AgentPlanController@parseCsvImport')->name('agent-plans.parseCsvImport');
    Route::post('agent-plans/process-csv-import', 'AgentPlanController@processCsvImport')->name('agent-plans.processCsvImport');
    Route::resource('agent-plans', 'AgentPlanController');

    // Packages Commission
    Route::post('packages-commissions/parse-csv-import', 'PackagesCommissionController@parseCsvImport')->name('packages-commissions.parseCsvImport');
    Route::post('packages-commissions/process-csv-import', 'PackagesCommissionController@processCsvImport')->name('packages-commissions.processCsvImport');
    Route::resource('packages-commissions', 'PackagesCommissionController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Agent Student
    Route::post('agent-students/parse-csv-import', 'AgentStudentController@parseCsvImport')->name('agent-students.parseCsvImport');
    Route::post('agent-students/process-csv-import', 'AgentStudentController@processCsvImport')->name('agent-students.processCsvImport');
    Route::resource('agent-students', 'AgentStudentController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Commission Statement
    Route::post('commission-statements/parse-csv-import', 'CommissionStatementController@parseCsvImport')->name('commission-statements.parseCsvImport');
    Route::post('commission-statements/process-csv-import', 'CommissionStatementController@processCsvImport')->name('commission-statements.processCsvImport');
    //Route::resource('commission-statements', 'CommissionStatementController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Commission Type Statement
    Route::post('commission-type-statements/parse-csv-import', 'CommissionTypeStatementController@parseCsvImport')->name('commission-type-statements.parseCsvImport');
    Route::post('commission-type-statements/process-csv-import', 'CommissionTypeStatementController@processCsvImport')->name('commission-type-statements.processCsvImport');
    Route::resource('commission-type-statements', 'CommissionTypeStatementController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);
    
    Route::get('system-calendar', 'SystemCalendarController@index')->name('systemCalendar');
    Route::get('global-search', 'GlobalSearchController@search')->name('globalSearch');

});

resources/views/home.blade.php
@extends('layouts.admin')
@include('layouts.styles')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="card mt-4">
                <div class="card-header font-semibold text-lg">{{ trans('global.general_report')}}</div>
                <div class="card-body">
                    @if(session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif  
                    <div class="intro-y report-box mt-12 sm:mt-4 sm:mb-1 xs:mt-4 xs:mb-1">
                        <div class="box py-0 xl:py-5 grid grid-cols-12 gap-0 divide-y xl:divide-y-0 divide-x divide-dashed divide-slate-200 dark:divide-white/5">
                            <div class="report-box__item py-5 xl:py-0 px-5 col-span-12 sm:col-span-6 xl:col-span-3">
                                <div class="report-box__content">
                                    <div class="flex">
                                        <div class="report-box__item__icon text-primary bg-pending/20 border border-pending/20 flex items-center justify-center rounded-full">
                                            <span class="material-symbols-outlined">emoji_people</span>
                                        </div>
                                    </div>
                                    <a href="{{ route("admin.agents.index", ['type' => 'dealer']) }}" class="text-decoration-none">
                                        <div class="text-lg font-medium leading-7 mt-6">{{trans('global.total_dealer')}}</div>
                                        <div class="text-slate-500 mt-1" id="total_dealers">{{ $total_dealers }}</div>
                                    </a>
                                </div>
                            </div>
                            <div class="report-box__item py-5 xl:py-0 px-5 sm:!border-t-0 col-span-12 sm:col-span-6 xl:col-span-3">
                                <div class="report-box__content">
                                    <div class="flex">
                                        <div class="report-box__item__icon text-pending bg-pending/20 border border-pending/20 flex items-center justify-center rounded-full">
                                            <span class="material-symbols-outlined">escalator_warning</span>
                                        </div>
                                    </div>
                                    <a href="{{ route("admin.agents.index", ['type' => 'franchiser']) }}" class="text-decoration-none">
                                        <div class="text-lg font-medium leading-7 mt-6">{{trans('global.total_franchiser')}}</div>
                                        <div class="text-slate-500 mt-1" id="total_franchiser">{{ $total_franchiser }}</div>
                                    </a>
                                </div>
                            </div>
                            <div class="report-box__item py-5 xl:py-0 px-5 col-span-12 sm:col-span-6 xl:col-span-3">
                                <div class="report-box__content">
                                    <div class="flex">
                                        <div class="report-box__item__icon text-success bg-pending/20 border border-pending/20 flex items-center justify-center rounded-full">
                                            <i class="fa fa-rocket "></i>
                                        </div>
                                    </div>
                                    <a href="{{ route("admin.agent-plans.index") }}" class="text-decoration-none">
                                        <div class="text-lg font-medium leading-7 mt-6">{{trans('global.total_dealer_plan')}}</div>
                                        <div class="text-slate-500 mt-1" id="total_dealer_price">{{ $total_dealer_price }}</div>
                                    </a>
                                </div>
                            </div>
                            <div class="report-box__item py-5 xl:py-0 px-5 col-span-12 sm:col-span-6 xl:col-span-3">
                                <div class="report-box__content">
                                    <div class="flex">
                                        <div class="report-box__item__icon text-warning bg-pending/20 border border-pending/20 flex items-center justify-center rounded-full">
                                            <i class="fa fa-paper-plane"></i>
                                        </div>
                                    </div>
                                    <a href="{{ route("admin.agent-plans.index") }}" class="text-decoration-none">
                                        <div class="text-lg font-medium leading-7 mt-6">{{trans('global.total_franchiser_plan')}}</div>
                                        <div class="text-slate-500 mt-1" id="total_franchiser_price">{{ $total_franchiser_price }}</div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
@parent
<script>
var speed = 50;

/* Call this function with a string containing the ID name to
 * the element containing the number you want to do a count animation on.*/
function incEltNbr(id, num) {
  elt = document.getElementById(id);
  endNbr = Number(document.getElementById(id).innerHTML);
  console.log(num);
  incNbrRec(0, num, endNbr, elt);
}

/*A recursive function to increase the number.*/
function incNbrRec(i, num, endNbr, elt) {
    i+= num ?? 1;
    if (i <= endNbr) {
        elt.innerHTML = i;
        setTimeout(function() {
            incNbrRec(i, num, endNbr, elt);
        }, speed);
    } else if(i > endNbr) {
        elt.innerHTML = endNbr;
    }
}

incEltNbr("total_dealers");
incEltNbr("total_franchiser"); 
incEltNbr("total_franchiser_price", 150); 
incEltNbr("total_dealer_price", 10);
</script>
@endsection