routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
// Settings
//Route::resource('/{type?}', 'SettingsController');
Route::group(['prefix' => 'settings', 'as' => 'settings.', 'middleware' => ['can:setting_access']], function () {
    Route::delete('destroy', 'SettingsController@massDestroy')->name('massDestroy');
    Route::prefix('{setting}/{group?}')->group(function () {
        Route::get('edit', 'SettingsController@edit')->name('edit');
        Route::get('show', 'SettingsController@show')->name('show');
        Route::match(['put', 'patch'], 'update', 'SettingsController@update')->name('update');
        Route::delete('delete', 'SettingsController@destroy')->name('destroy');
    });
    Route::prefix('{group?}')->group(function () {
        Route::get('/', 'SettingsController@index')->name('index');
        Route::get('create', 'SettingsController@create')->name('create');
        Route::post('store', 'SettingsController@store')->name('store');
    });
    Route::get('{condition?}/clear-cache', 'SettingsController@clearCache')->name('clear-cache');
    Route::post('{condition?}/save-settings', 'SettingsController@saveConditionSettings')->name('save-settings');
});

// Agent
Route::group(['prefix' => 'agents/{type}', 'as' => 'agents.'], function () {
    Route::get('/', 'AgentsController@index')->name('index');
    Route::get('create', 'AgentsController@create')->name('create');
    Route::post('store', 'AgentsController@store')->name('store');
    /* Route::prefix('{user}')->group(function () {
        Route::get('edit', 'AgentsController@edit')->name('edit');
        Route::match(['put', 'patch'], 'update', 'AgentsController@update')->name('update');
    }); */
});
Route::group(['prefix' => 'agents/{user}', 'as' => 'agents.'], function () {
    Route::prefix('{type?}')->group(function () {
        Route::get('edit', 'AgentsController@edit')->name('edit');
        Route::match(['put', 'patch'], 'update', 'AgentsController@update')->name('update');
    });
});
// Commission
Route::group(['prefix' => 'commissions', 'as' => 'commissions.', 'middleware' => ['can:commission_access']], function () {
    Route::delete('destroy', 'CommissionController@massDestroy')->name('massDestroy');
    Route::post('parse-csv-import', 'CommissionController@parseCsvImport')->name('parseCsvImport');
    Route::post('process-csv-import', 'CommissionController@processCsvImport')->name('processCsvImport');
    Route::post('getCommissionFields', 'CommissionController@returnCommissionFields')->name('returnCommissionFields');
    Route::prefix('{commission}/{type?}')->group(function () {
        Route::get('edit', 'CommissionController@edit')->name('edit');
        Route::get('show', 'CommissionController@show')->name('show');
        Route::match(['put', 'patch'], 'update', 'CommissionController@update')->name('update');
        Route::delete('delete', 'CommissionController@destroy')->name('destroy');
    });
    Route::prefix('{type?}')->group(function () {
        Route::get('/', 'CommissionController@index')->name('index');
        Route::get('create', 'CommissionController@create')->name('create');
        Route::post('store', 'CommissionController@store')->name('store');
    });
}); //Route::resource('commissions/{type?}', 'CommissionController');

// Commission Statement
Route::group(['prefix' => 'commission-statements/{type}', 'as' => 'commission-statements.'], function () {
    Route::get('/', 'CommissionStatementController@index')->name('index');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }
    return redirect()->route('admin.home');
});

Route::group(['namespace' => 'Franchiser'], function () {
    // agent email varification
    Route::get('franchiser-agent/verify/{dataSource}', 'FranchiserAgentController@verify')->name('franchiser-agent.verify');
})
;
//Color Scheme
Route::get('color-scheme-switcher/{color_scheme}','ColorSchemeController@switch')->name('color-scheme-switcher');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', '2fa']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Students
    Route::delete('students/destroy', 'StudentsController@massDestroy')->name('students.massDestroy');
    Route::resource('students', 'StudentsController');

    // Mlm Level
    Route::post('mlm-levels/parse-csv-import', 'MlmLevelController@parseCsvImport')->name('mlm-levels.parseCsvImport');
    Route::post('mlm-levels/process-csv-import', 'MlmLevelController@processCsvImport')->name('mlm-levels.processCsvImport');
    Route::resource('mlm-levels', 'MlmLevelController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Dealer
    Route::get('dealers/{user}/edit', 'DealerController@edit')->name('dealers.edit');
    Route::put('dealers/{user}/update', 'DealerController@update')->name('dealers.update');
    Route::resource('dealers', 'DealerController', ['except' => ['edit', 'update', 'show', 'destroy']]);

    // Agent Plan
    Route::delete('agent-plans/destroy', 'AgentPlanController@massDestroy')->name('agent-plans.massDestroy');
    Route::post('agent-plans/media', 'AgentPlanController@storeMedia')->name('agent-plans.storeMedia');
    Route::post('agent-plans/ckmedia', 'AgentPlanController@storeCKEditorImages')->name('agent-plans.storeCKEditorImages');
    Route::post('agent-plans/parse-csv-import', 'AgentPlanController@parseCsvImport')->name('agent-plans.parseCsvImport');
    Route::post('agent-plans/process-csv-import', 'AgentPlanController@processCsvImport')->name('agent-plans.processCsvImport');
    Route::resource('agent-plans', 'AgentPlanController');

    // Packages Commission
    Route::post('packages-commissions/parse-csv-import', 'PackagesCommissionController@parseCsvImport')->name('packages-commissions.parseCsvImport');
    Route::post('packages-commissions/process-csv-import', 'PackagesCommissionController@processCsvImport')->name('packages-commissions.processCsvImport');
    Route::resource('packages-commissions', 'PackagesCommissionController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Agent Student
    Route::post('agent-students/parse-csv-import', 'AgentStudentController@parseCsvImport')->name('agent-students.parseCsvImport');
    Route::post('agent-students/process-csv-import', 'AgentStudentController@processCsvImport')->name('agent-students.processCsvImport');
    Route::resource('agent-students', 'AgentStudentController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Commission Statement
    Route::post('commission-statements/parse-csv-import', 'CommissionStatementController@parseCsvImport')->name('commission-statements.parseCsvImport');
    Route::post('commission-statements/process-csv-import', 'CommissionStatementController@processCsvImport')->name('commission-statements.processCsvImport');
    //Route::resource('commission-statements', 'CommissionStatementController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Commission Type Statement
    Route::post('commission-type-statements/parse-csv-import', 'CommissionTypeStatementController@parseCsvImport')->name('commission-type-statements.parseCsvImport');
    Route::post('commission-type-statements/process-csv-import', 'CommissionTypeStatementController@processCsvImport')->name('commission-type-statements.processCsvImport');
    Route::resource('commission-type-statements', 'CommissionTypeStatementController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);
    
    Route::get('system-calendar', 'SystemCalendarController@index')->name('systemCalendar');
    Route::get('global-search', 'GlobalSearchController@search')->name('globalSearch');

});

app/Models/PackagesCommission.php
<?php

namespace App\Models;

use \DateTimeInterface;
use App\Traits\Auditable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class PackagesCommission extends Model
{
    use SoftDeletes;
    use Auditable;
    use HasFactory;

    public $table = 'packages_commissions';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'tuition_package_efk',
        'commission_id',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function commission()
    {
        return $this->belongsTo(Commission::class, 'commission_id')->withTrashed();
    }
    
    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/PackagesCommissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Models\PackagesCommission;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class PackagesCommissionController extends Controller
{
    use CsvImportTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('packages_commission_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = PackagesCommission::with(['commission'])->select(sprintf('%s.*', (new PackagesCommission())->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate = 'packages_commission_show';
                $editGate = 'packages_commission_edit';
                $deleteGate = 'packages_commission_delete';
                $crudRoutePart = 'packages-commissions';

                return view('partials.datatablesActions', compact(
                'viewGate',
                'editGate',
                'deleteGate',
                'crudRoutePart',
                'row'
            ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : '';
            });
            $table->editColumn('tuition_package_efk', function ($row) {
                return $row->tuition_package_efk ? $row->tuition_package_efk : '';
            });
            $table->addColumn('commission_commission', function ($row) {
                return $row->commission ? $row->commission->commission : '';
            });

            $table->editColumn('commission.level', function ($row) {
                return $row->commission ? (is_string($row->commission) ? $row->commission : $row->commission->level) : '';
            });

            $table->rawColumns(['actions', 'placeholder', 'commission']);

            return $table->make(true);
        }

        return view('admin.packagesCommissions.index');
    }
}

resources/views/admin/packagesCommissions/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header font-semibold text-lg">
        {{ trans('global.create') }} {{ trans('cruds.packagesCommission.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.packages-commissions.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="tuition_package_efk">{{ trans('cruds.packagesCommission.fields.tuition_package_efk') }}</label>
                <input class="form-control {{ $errors->has('tuition_package_efk') ? 'is-invalid' : '' }}" type="number" name="tuition_package_efk" id="tuition_package_efk" value="{{ old('tuition_package_efk', '') }}" step="1">
                @if($errors->has('tuition_package_efk'))
                    <div class="invalid-feedback">
                        {{ $errors->first('tuition_package_efk') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.packagesCommission.fields.tuition_package_efk_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="commission_id">{{ trans('cruds.packagesCommission.fields.commission') }}</label>
                <select class="form-control select2 {{ $errors->has('commission') ? 'is-invalid' : '' }}" name="commission_id" id="commission_id">
                    @foreach($commissions as $id => $entry)
                        <option value="{{ $id }}" {{ old('commission_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('commission'))
                    <div class="invalid-feedback">
                        {{ $errors->first('commission') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.packagesCommission.fields.commission_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/packagesCommissions/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header font-semibold text-lg">
        {{ trans('global.edit') }} {{ trans('cruds.packagesCommission.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.packages-commissions.update", [$packagesCommission->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="tuition_package_efk">{{ trans('cruds.packagesCommission.fields.tuition_package_efk') }}</label>
                <input class="form-control {{ $errors->has('tuition_package_efk') ? 'is-invalid' : '' }}" type="number" name="tuition_package_efk" id="tuition_package_efk" value="{{ old('tuition_package_efk', $packagesCommission->tuition_package_efk) }}" step="1">
                @if($errors->has('tuition_package_efk'))
                    <div class="invalid-feedback">
                        {{ $errors->first('tuition_package_efk') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.packagesCommission.fields.tuition_package_efk_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="commission_id">{{ trans('cruds.packagesCommission.fields.commission') }}</label>
                <select class="form-control select2 {{ $errors->has('commission') ? 'is-invalid' : '' }}" name="commission_id" id="commission_id">
                    @foreach($commissions as $id => $entry)
                        <option value="{{ $id }}" {{ (old('commission_id') ? old('commission_id') : $packagesCommission->commission->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('commission'))
                    <div class="invalid-feedback">
                        {{ $errors->first('commission') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.packagesCommission.fields.commission_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/packagesCommissions/index.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header font-semibold text-lg">
        {{ trans('cruds.packagesCommission.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <table class=" table table-bordered table-striped table-hover ajaxTable datatable datatable-PackagesCommission">
            <thead>
                <tr>
                    <th width="10">

                    </th>
                    <th>
                        {{ trans('cruds.fields.id') }}
                    </th>
                    <th>
                        {{ trans('cruds.packagesCommission.fields.tuition_package_efk') }}
                    </th>
                    <th>
                        {{ trans('cruds.packagesCommission.fields.commission') }}
                    </th>
                    <th>
                        {{ trans('cruds.commission.fields.level') }}
                    </th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
  
  let dtOverrideGlobals = {
    buttons: dtButtons,
    processing: true,
    serverSide: true,
    retrieve: true,
    aaSorting: [],
    ajax: "{{ route('admin.packages-commissions.index') }}",
    columns: [
      { data: 'placeholder', name: 'placeholder' },
{ data: 'id', name: 'id' },
{ data: 'tuition_package_efk', name: 'tuition_package_efk' },
{ data: 'commission_commission', name: 'commission.commission' },
{ data: 'commission.level', name: 'commission.level' },
{ data: 'actions', name: '{{ trans('global.actions') }}' }
    ],
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  };
  let table = $('.datatable-PackagesCommission').DataTable(dtOverrideGlobals);
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
});

</script>
@endsection

resources/views/admin/packagesCommissions/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header font-semibold text-lg">
        {{ trans('global.show') }} {{ trans('cruds.packagesCommission.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.packages-commissions.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.fields.id') }}
                        </th>
                        <td>
                            {{ $packagesCommission->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.packagesCommission.fields.tuition_package_efk') }}
                        </th>
                        <td>
                            {{ $packagesCommission->tuition_package_efk }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.packagesCommission.fields.commission') }}
                        </th>
                        <td>
                            {{ $packagesCommission->commission->commission ?? '' }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.packages-commissions.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection