routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
// Settings
//Route::resource('/{type?}', 'SettingsController');
Route::group(['prefix' => 'settings', 'as' => 'settings.', 'middleware' => ['can:setting_access']], function () {
    Route::delete('destroy', 'SettingsController@massDestroy')->name('massDestroy');
    Route::prefix('{setting}/{group?}')->group(function () {
        Route::get('edit', 'SettingsController@edit')->name('edit');
        Route::get('show', 'SettingsController@show')->name('show');
        Route::match(['put', 'patch'], 'update', 'SettingsController@update')->name('update');
        Route::delete('delete', 'SettingsController@destroy')->name('destroy');
    });
    Route::prefix('{group?}')->group(function () {
        Route::get('/', 'SettingsController@index')->name('index');
        Route::get('create', 'SettingsController@create')->name('create');
        Route::post('store', 'SettingsController@store')->name('store');
    });
    Route::get('{condition?}/clear-cache', 'SettingsController@clearCache')->name('clear-cache');
    Route::post('{condition?}/save-settings', 'SettingsController@saveConditionSettings')->name('save-settings');
});

// Agent
Route::group(['prefix' => 'agents/{type}', 'as' => 'agents.'], function () {
    Route::get('/', 'AgentsController@index')->name('index');
    Route::get('create', 'AgentsController@create')->name('create');
    Route::post('store', 'AgentsController@store')->name('store');
    /* Route::prefix('{user}')->group(function () {
        Route::get('edit', 'AgentsController@edit')->name('edit');
        Route::match(['put', 'patch'], 'update', 'AgentsController@update')->name('update');
    }); */
});
Route::group(['prefix' => 'agents/{user}', 'as' => 'agents.'], function () {
    Route::prefix('{type?}')->group(function () {
        Route::get('edit', 'AgentsController@edit')->name('edit');
        Route::match(['put', 'patch'], 'update', 'AgentsController@update')->name('update');
    });
});
// Commission
Route::group(['prefix' => 'commissions', 'as' => 'commissions.', 'middleware' => ['can:commission_access']], function () {
    Route::delete('destroy', 'CommissionController@massDestroy')->name('massDestroy');
    Route::post('parse-csv-import', 'CommissionController@parseCsvImport')->name('parseCsvImport');
    Route::post('process-csv-import', 'CommissionController@processCsvImport')->name('processCsvImport');
    Route::post('getCommissionFields', 'CommissionController@returnCommissionFields')->name('returnCommissionFields');
    Route::prefix('{commission}/{type?}')->group(function () {
        Route::get('edit', 'CommissionController@edit')->name('edit');
        Route::get('show', 'CommissionController@show')->name('show');
        Route::match(['put', 'patch'], 'update', 'CommissionController@update')->name('update');
        Route::delete('delete', 'CommissionController@destroy')->name('destroy');
    });
    Route::prefix('{type?}')->group(function () {
        Route::get('/', 'CommissionController@index')->name('index');
        Route::get('create', 'CommissionController@create')->name('create');
        Route::post('store', 'CommissionController@store')->name('store');
    });
}); //Route::resource('commissions/{type?}', 'CommissionController');

// Commission Statement
Route::group(['prefix' => 'commission-statements/{type}', 'as' => 'commission-statements.'], function () {
    Route::get('/', 'CommissionStatementController@index')->name('index');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }
    return redirect()->route('admin.home');
});

Route::group(['namespace' => 'Franchiser'], function () {
    // agent email varification
    Route::get('franchiser-agent/verify/{dataSource}', 'FranchiserAgentController@verify')->name('franchiser-agent.verify');
})
;
//Color Scheme
Route::get('color-scheme-switcher/{color_scheme}','ColorSchemeController@switch')->name('color-scheme-switcher');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', '2fa']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Students
    Route::delete('students/destroy', 'StudentsController@massDestroy')->name('students.massDestroy');
    Route::resource('students', 'StudentsController');

    // Mlm Level
    Route::post('mlm-levels/parse-csv-import', 'MlmLevelController@parseCsvImport')->name('mlm-levels.parseCsvImport');
    Route::post('mlm-levels/process-csv-import', 'MlmLevelController@processCsvImport')->name('mlm-levels.processCsvImport');
    Route::resource('mlm-levels', 'MlmLevelController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Dealer
    Route::get('dealers/{user}/edit', 'DealerController@edit')->name('dealers.edit');
    Route::put('dealers/{user}/update', 'DealerController@update')->name('dealers.update');
    Route::resource('dealers', 'DealerController', ['except' => ['edit', 'update', 'show', 'destroy']]);

    // Agent Plan
    Route::delete('agent-plans/destroy', 'AgentPlanController@massDestroy')->name('agent-plans.massDestroy');
    Route::post('agent-plans/media', 'AgentPlanController@storeMedia')->name('agent-plans.storeMedia');
    Route::post('agent-plans/ckmedia', 'AgentPlanController@storeCKEditorImages')->name('agent-plans.storeCKEditorImages');
    Route::post('agent-plans/parse-csv-import', 'AgentPlanController@parseCsvImport')->name('agent-plans.parseCsvImport');
    Route::post('agent-plans/process-csv-import', 'AgentPlanController@processCsvImport')->name('agent-plans.processCsvImport');
    Route::resource('agent-plans', 'AgentPlanController');

    // Packages Commission
    Route::post('packages-commissions/parse-csv-import', 'PackagesCommissionController@parseCsvImport')->name('packages-commissions.parseCsvImport');
    Route::post('packages-commissions/process-csv-import', 'PackagesCommissionController@processCsvImport')->name('packages-commissions.processCsvImport');
    Route::resource('packages-commissions', 'PackagesCommissionController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Agent Student
    Route::post('agent-students/parse-csv-import', 'AgentStudentController@parseCsvImport')->name('agent-students.parseCsvImport');
    Route::post('agent-students/process-csv-import', 'AgentStudentController@processCsvImport')->name('agent-students.processCsvImport');
    Route::resource('agent-students', 'AgentStudentController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Commission Statement
    Route::post('commission-statements/parse-csv-import', 'CommissionStatementController@parseCsvImport')->name('commission-statements.parseCsvImport');
    Route::post('commission-statements/process-csv-import', 'CommissionStatementController@processCsvImport')->name('commission-statements.processCsvImport');
    //Route::resource('commission-statements', 'CommissionStatementController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);

    // Commission Type Statement
    Route::post('commission-type-statements/parse-csv-import', 'CommissionTypeStatementController@parseCsvImport')->name('commission-type-statements.parseCsvImport');
    Route::post('commission-type-statements/process-csv-import', 'CommissionTypeStatementController@processCsvImport')->name('commission-type-statements.processCsvImport');
    Route::resource('commission-type-statements', 'CommissionTypeStatementController', ['except' => ['create', 'store', 'edit', 'update', 'show', 'destroy']]);
    
    Route::get('system-calendar', 'SystemCalendarController@index')->name('systemCalendar');
    Route::get('global-search', 'GlobalSearchController@search')->name('globalSearch');

});

app/Models/AgentPlan.php
<?php

namespace App\Models;

use \DateTimeInterface;
use App\Traits\Auditable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Modules\SsoClient\Entities\Role;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class AgentPlan extends Model implements HasMedia
{
    use SoftDeletes;
    use InteractsWithMedia;
    use Auditable;
    use HasFactory;

    public $table = 'agent_plans';

    public static $searchable = [
        'name',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'price',
        'description',
        'roles_id',
        'commissionable_level',
        'refundable',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')->fit('crop', 50, 50);
        $this->addMediaConversion('preview')->fit('crop', 120, 120);
    }

    public function currentPlanMlmLevels()
    {
        return $this->hasMany(MlmLevel::class, 'current_plan_id', 'id');
    }

    public function agentPlanCommissions()
    {
        return $this->hasMany(Commission::class, 'agent_plan_id', 'id');
    }

    public function roles()
    {
        return $this->belongsTo(Role::class, 'roles_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/AgentPlanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyAgentPlanRequest;
use App\Http\Requests\StoreAgentPlanRequest;
use App\Http\Requests\UpdateAgentPlanRequest;
use App\Models\AgentPlan;
use App\Models\AppSettings;
use Gate;
use Illuminate\Http\Request;
use Modules\SsoClient\Entities\Role;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class AgentPlanController extends Controller
{
    use MediaUploadingTrait;
    use CsvImportTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('agent_plan_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $collections = AgentPlan::with(['roles'])->select(sprintf('%s.*', (new AgentPlan())->table))->get();
            $table = Datatables::of($collections);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate = 'agent_plan_show';
                $editGate = 'agent_plan_edit';
                $deleteGate = 'agent_plan_delete';
                $crudRoutePart = 'agent-plans';

                return view('partials.datatablesActions', compact(
                'viewGate',
                'editGate',
                'deleteGate',
                'crudRoutePart',
                'row'
            ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : '';
            });
            $table->editColumn('name', function ($row) {
                return $row->name ? $row->name : '';
            });
            $table->editColumn('price', function ($row) {
                return $row->price ? $row->price : '';
            });
            $table->addColumn('roles_title', function ($row) {
                return $row->roles ? $row->roles->title : '';
            });

            $table->editColumn('commissionable_level', function ($row) {
                return $row->commissionable_level ? $row->commissionable_level : '';
            });
            $table->editColumn('refundable', function ($row) {
                return '<input type="checkbox" disabled ' . ($row->refundable ? 'checked' : null) . '>';
            });

            $table->rawColumns(['actions', 'placeholder', 'roles', 'refundable']);

            return $table->make(true);
        }

        return view('admin.agentPlans.index');
    }

    public function create()
    {
        abort_if(Gate::denies('agent_plan_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $roles = Role::pluck('title', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.agentPlans.create', compact('roles'));
    }

    public function store(StoreAgentPlanRequest $request)
    {
        $agentPlan = AgentPlan::create($request->all());

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $agentPlan->id]);
        }

        return redirect()->route('admin.agent-plans.index');
    }

    public function edit(AgentPlan $agentPlan)
    {
        abort_if(Gate::denies('agent_plan_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $roles = Role::pluck('title', 'id')->prepend(trans('global.pleaseSelect'), '');

        $agentPlan->load('roles');

        return view('admin.agentPlans.edit', compact('agentPlan', 'roles'));
    }

    public function update(UpdateAgentPlanRequest $request, AgentPlan $agentPlan)
    {
        $settings = [
            'max_refundable_amount',
            'package_refund_period',
            'package_refund_target',
        ];
        if(!isset($request->refundable)) {
            $request->merge([
                'refundable'=>0
            ]);
        }
        foreach ($settings as $index) {
            if(isset($request->{$index}) && count($request->{$index}) > 0 && isset($request->{$index}[array_keys($request->{$index})[0]])){
                $key = array_keys($request->{$index})[0];
                AppSettings::updateOrCreate([
                    'group'=>'condition',
                    'locked' => 0,
                    'name'=> $index.'_'.$key,
                ], [
                    'payload'=> $request->{$index}[$key],
                ]);
            }
        }
        $agentPlan->update($request->all());

        return redirect()->route('admin.agent-plans.index');
    }

    public function show(AgentPlan $agentPlan)
    {
        abort_if(Gate::denies('agent_plan_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $agentPlan->load('roles', 'currentPlanMlmLevels', 'agentPlanCommissions');

        return view('admin.agentPlans.show', compact('agentPlan'));
    }

    public function destroy(AgentPlan $agentPlan)
    {
        abort_if(Gate::denies('agent_plan_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $agentPlan->delete();

        return back();
    }

    public function massDestroy(MassDestroyAgentPlanRequest $request)
    {
        AgentPlan::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('agent_plan_create') && Gate::denies('agent_plan_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new AgentPlan();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

resources/views/admin/agentPlans/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="card">
    <div class="card-header font-semibold text-lg">
        {{ trans('global.create') }} {{ trans('cruds.agentPlan.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.agent-plans.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                <div class="invalid-feedback">
                    {{ $errors->first('name') }}
                </div>
                @endif
                <span class="help-block">{{ trans('cruds.fields.name_helper') }}</span>
            </div>
            <div class="form-group row">
                <div class="col">
                    <label class="required" for="price">{{ trans('cruds.agentPlan.fields.price') }}</label>
                    <input class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}" type="number" name="price" id="price" value="{{ old('price', '0.00') }}" step="0.01" required>
                    @if($errors->has('price'))
                    <div class="invalid-feedback">
                        {{ $errors->first('price') }}
                    </div>
                    @endif
                    <span class="help-block">{{ trans('cruds.agentPlan.fields.price_helper') }}</span>
                </div>
                <div class="col-auto">
                    <label class="row justify-content-center">{{ trans('cruds.agentPlan.fields.refundable') }}</label>
                    <div class="custom-control custom-switch custom-switch-lg" data-toggle="toggle">
                        <input type="checkbox" class="custom-control-input" id="refundable" name="refundable" type="checkbox" data-toggle="toggle" value="{{ old('refundable', 0) }}" {{ old('refundable', 0) === 1 ? 'checked' : '' }}>
                        <label class="custom-control-label" for="refundable"></label>
                    </div>
                    @if($errors->has('refundable'))
                        <div class="invalid-feedback">
                            {{ $errors->first('refundable') }}
                        </div>
                    @endif
                    <span class="help-block">{{ trans('cruds.agentPlan.fields.refundable_helper') }}</span>
                </div>
            </div>
            <div class="card-body refundable-form" id="refundable-form" style="display:none">
                <div class="form-group">
                    <label class="required" for="max_refundable_amount[]">{{ trans('settings.condition.max_refundable_amount') }} {{ trans('global.rm') }}</label>
                    <input class="form-control {{ $errors->has('max_refundable_amount[]') ? 'is-invalid' : '' }}" type="number" name="max_refundable_amount[]" id="max_refundable_amount[]" value="{{ old('max_refundable_amount_') }}">
                </div>
                <div class="form-group">
                    <label class="required" for="package_refund_period[]">{{ trans('settings.condition.refund_period') }} {{ trans('global.months') }}</label>
                    <input class="form-control {{ $errors->has('package_refund_period[]') ? 'is-invalid' : '' }}" min="1" max="99" type="number" name="package_refund_period[]" id="package_refund_period[]" value="{{ old('package_refund_period[]') }}">
                </div>
                <div class="form-group">
                    <label class="required" for="package_refund_target[]">{{ trans('settings.condition.target_downline') }}</label>
                    <input class="form-control {{ $errors->has('package_refund_target[]') ? 'is-invalid' : '' }}" min="0" max="99" type="number" name="package_refund_target[]" id="package_refund_target[]" value="{{ old('package_refund_target[]') }}">
                </div>
            </div>
            <div class="form-group">
                <label for="description">{{ trans('cruds.agentPlan.fields.description') }}</label>
                <textarea class="form-control ckeditor {{ $errors->has('description') ? 'is-invalid' : '' }}" name="description" id="description">{!! old('description') !!}</textarea>
                @if($errors->has('description'))
                <div class="invalid-feedback">
                    {{ $errors->first('description') }}
                </div>
                @endif
                <span class="help-block">{{ trans('cruds.agentPlan.fields.description_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="roles_id">{{ trans('cruds.agentPlan.fields.roles') }}</label>
                <select class="form-control select2 {{ $errors->has('roles') ? 'is-invalid' : '' }}" name="roles_id" id="roles_id">
                    @foreach($roles as $id => $entry)
                    <option value="{{ $id }}" {{ $id == '' ? 'disabled' : '' }} {{ old('roles_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('roles'))
                <div class="invalid-feedback">
                    {{ $errors->first('roles') }}
                </div>
                @endif
                <span class="help-block">{{ trans('cruds.agentPlan.fields.roles_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="commissionable_level">{{ trans('cruds.agentPlan.fields.commissionable_level') }}</label>
                <input class="form-control {{ $errors->has('commissionable_level') ? 'is-invalid' : '' }}" type="number" name="commissionable_level" id="commissionable_level" value="{{ old('commissionable_level', '2') }}" step="1" required>
                @if($errors->has('commissionable_level'))
                <div class="invalid-feedback">
                    {{ $errors->first('commissionable_level') }}
                </div>
                @endif
                <span class="help-block">{{ trans('cruds.agentPlan.fields.commissionable_level_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    $(document).ready(function() {
        function SimpleUploadAdapter(editor) {
            editor.plugins.get('FileRepository').createUploadAdapter = function(loader) {
                return {
                    upload: function() {
                        return loader.file
                            .then(function(file) {
                                return new Promise(function(resolve, reject) {
                                    // Init request
                                    var xhr = new XMLHttpRequest();
                                    xhr.open('POST', '{{ route("admin.agent-plans.storeCKEditorImages") }}', true);
                                    xhr.setRequestHeader('x-csrf-token', window._token);
                                    xhr.setRequestHeader('Accept', 'application/json');
                                    xhr.responseType = 'json';

                                    // Init listeners
                                    var genericErrorText = `Couldn't upload file: ${ file.name }.`;
                                    xhr.addEventListener('error', function() {
                                        reject(genericErrorText)
                                    });
                                    xhr.addEventListener('abort', function() {
                                        reject()
                                    });
                                    xhr.addEventListener('load', function() {
                                        var response = xhr.response;

                                        if (!response || xhr.status !== 201) {
                                            return reject(response && response.message ? `${genericErrorText}\n${xhr.status} ${response.message}` : `${genericErrorText}\n ${xhr.status} ${xhr.statusText}`);
                                        }

                                        $('form').append('<input type="hidden" name="ck-media[]" value="' + response.id + '">');

                                        resolve({
                                            default: response.url
                                        });
                                    });

                                    if (xhr.upload) {
                                        xhr.upload.addEventListener('progress', function(e) {
                                            if (e.lengthComputable) {
                                                loader.uploadTotal = e.total;
                                                loader.uploaded = e.loaded;
                                            }
                                        });
                                    }

                                    // Send request
                                    var data = new FormData();
                                    data.append('upload', file);
                                    data.append('crud_id', '{{ $agentPlan->id ?? 0 }}');
                                    xhr.send(data);
                                });
                            })
                    }
                };
            }
        }

        var allEditors = document.querySelectorAll('.ckeditor');
        for (var i = 0; i < allEditors.length; ++i) {
            ClassicEditor.create(
                allEditors[i], {
                    extraPlugins: [SimpleUploadAdapter]
                }
            );
        }

        $('#refundable').click(function () {
            $('#refundable-form').toggle($('#refundable').is(':checked'));
            $('#refundable-form :input').prop('required',$('#refundable').is(':checked'));
        });
    });

</script>

@endsection

resources/views/admin/agentPlans/index.blade.php
@extends('layouts.admin')
@section('content')
@can('agent_plan_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success add_condition" href="{{ route('admin.agent-plans.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.agentPlan.title_singular') }}
            </a>
            <button class="btn btn-warning" data-toggle="modal" data-target="#csvImportModal">
                {{ trans('global.app_csvImport') }}
            </button>
            @include('csvImport.modal', ['model' => 'AgentPlan', 'route' => 'admin.agent-plans.parseCsvImport'])
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header font-semibold text-lg">
        {{ trans('cruds.agentPlan.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <table class=" table table-bordered table-striped table-hover ajaxTable datatable datatable-AgentPlan">
            <thead>
                <tr>
                    <th width="10">

                    </th>
                    <th>
                        {{ trans('cruds.fields.id') }}
                    </th>
                    <th>
                        {{ trans('cruds.fields.name') }}
                    </th>
                    <th>
                        {{ trans('cruds.agentPlan.fields.price') }}
                    </th>
                    <th>
                        {{ trans('cruds.agentPlan.fields.roles') }}
                    </th>
                    <th>
                        {{ trans('cruds.agentPlan.fields.commissionable_level') }}
                    </th>
                    <th>
                        {{ trans('cruds.agentPlan.fields.refundable') }}
                    </th>
                    <th>
                        &nbsp;
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('agent_plan_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}';
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.agent-plans.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).data(), function (entry) {
          return entry.id
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  let dtOverrideGlobals = {
    buttons: dtButtons,
    processing: true,
    serverSide: true,
    retrieve: true,
    aaSorting: [],
    ajax: "{{ route('admin.agent-plans.index') }}",
    columns: [
      { data: 'placeholder', name: 'placeholder' },
{ data: 'id', name: 'id' },
{ data: 'name', name: 'name' },
{ data: 'price', name: 'price' },
{ data: 'roles_title', name: 'roles_title' },
{ data: 'commissionable_level', name: 'commissionable_level' },
{ data: 'refundable', name: 'refundable' },
{ data: 'actions', name: '{{ trans('global.actions') }}' }
    ],
    orderCellsTop: true,
    order: [[ 2, 'desc' ]],
    pageLength: 10,
  };
  let table = $('.datatable-AgentPlan').DataTable(dtOverrideGlobals);
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
});

</script>
@endsection